services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      USERMYSQL: root
      PASSWORD: toor
      HOST: localhost
      PORT: 3306
      DATABASE: base
      DEBUG: True
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: base
      MYSQL_USER: user
      MYSQL_PASSWORD: toor
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

volumes:
  db_data: