name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: |
        cd ./api && docker-compose up -d

    - name: Run tests
      run: |
        docker exec -it app pytest