name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set Environment Variables
      run: |
        cd ./api
      env:
        USERMYSQL: root
        PASSWORD: toor
        HOST: localhost
        PORT: 3306
        DATABASE: base
        DEBUG: True
        
    - name: Build Docker Image
      run: |
        docker-compose up -d

    - name: Run tests
      run: |
        docker exec -it api pytest